//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevToys.PolishDataGen.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PolishDataGen {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PolishDataGen() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevToys.PolishDataGen.Strings.PolishDataGen", typeof(PolishDataGen).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows generation of PESEL, NIP, REGON.
        /// </summary>
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when enabled app will run k = 1 + 3.3 * Log10(Number) jobs.
        /// </summary>
        internal static string CliEnableMultithreading {
            get {
                return ResourceManager.GetString("CliEnableMultithreading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select id type. Current available options are: pesel | nip | regon | regon-long | identity-card-number.
        /// </summary>
        internal static string CliIdType {
            get {
                return ResourceManager.GetString("CliIdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With such large numbers it is recommended to use the CLI version.
        /// </summary>
        internal static string CliInfoBarContent {
            get {
                return ResourceManager.GetString("CliInfoBarContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string CliInfoBarTitle {
            get {
                return ResourceManager.GetString("CliInfoBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string CliMultiLineTextInputTitle {
            get {
                return ResourceManager.GetString("CliMultiLineTextInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the number of data to be generated.
        /// </summary>
        internal static string CliNumberPropertyDescription {
            get {
                return ResourceManager.GetString("CliNumberPropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to define output file path.
        /// </summary>
        internal static string CliOutputFilePath {
            get {
                return ResourceManager.GetString("CliOutputFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tool allows validation of Polish identification numbers. It is possible to return a short or detailed description (error list)..
        /// </summary>
        internal static string CliValidatorDescription {
            get {
                return ResourceManager.GetString("CliValidatorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a detailed list of validation errors.
        /// </summary>
        internal static string CliValidatorExtendedDetailsDescription {
            get {
                return ResourceManager.GetString("CliValidatorExtendedDetailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input field for value to be checked.
        /// </summary>
        internal static string CliValidatorInput {
            get {
                return ResourceManager.GetString("CliValidatorInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows you to return an integer as the result. 1 - True, 0 - False, -1 - Error.
        /// </summary>
        internal static string CliValidatorIntegerAsResult {
            get {
                return ResourceManager.GetString("CliValidatorIntegerAsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library for generating correct Polish identifiers: PESEL, NIP, REGON and more. Perfect for testing and validating systems..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear memory.
        /// </summary>
        internal static string GuiClearMemoryButtonLabel {
            get {
                return ResourceManager.GetString("GuiClearMemoryButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string GuiGenerateButtonLabel {
            get {
                return ResourceManager.GetString("GuiGenerateButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows generation of Polish identifiers: PESEL, NIP, REGON and more. Perfect for testing and validating systems..
        /// </summary>
        internal static string GuiGeneratorDescription {
            get {
                return ResourceManager.GetString("GuiGeneratorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Card Number.
        /// </summary>
        internal static string GuiIdTypeIdentityCardNumber {
            get {
                return ResourceManager.GetString("GuiIdTypeIdentityCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP.
        /// </summary>
        internal static string GuiIdTypeNip {
            get {
                return ResourceManager.GetString("GuiIdTypeNip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESEL.
        /// </summary>
        internal static string GuiIdTypePesel {
            get {
                return ResourceManager.GetString("GuiIdTypePesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON (9 digits).
        /// </summary>
        internal static string GuiIdTypeRegon {
            get {
                return ResourceManager.GetString("GuiIdTypeRegon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON (14 digits).
        /// </summary>
        internal static string GuiIdTypeRegonLong {
            get {
                return ResourceManager.GetString("GuiIdTypeRegonLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of data to generate.
        /// </summary>
        internal static string GuiNumberInputLabel {
            get {
                return ResourceManager.GetString("GuiNumberInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        internal static string GuiValidateButtonLabel {
            get {
                return ResourceManager.GetString("GuiValidateButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows validation of Polish identification numbers. .
        /// </summary>
        internal static string GuiValidationDescription {
            get {
                return ResourceManager.GetString("GuiValidationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error.
        /// </summary>
        internal static string GuiValidationErrorTitle {
            get {
                return ResourceManager.GetString("GuiValidationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is invalid.
        /// </summary>
        internal static string GuiValidationIsInvalidLabel {
            get {
                return ResourceManager.GetString("GuiValidationIsInvalidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is valid.
        /// </summary>
        internal static string GuiValidationIsValidLabel {
            get {
                return ResourceManager.GetString("GuiValidationIsValidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish ids validation.
        /// </summary>
        internal static string GuiValidationLongDisplayTitle {
            get {
                return ResourceManager.GetString("GuiValidationLongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select validation type.
        /// </summary>
        internal static string GuiValidationSelectTypeLabel {
            get {
                return ResourceManager.GetString("GuiValidationSelectTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish Data Validation.
        /// </summary>
        internal static string GuiValidationShortDisplayTitle {
            get {
                return ResourceManager.GetString("GuiValidationShortDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string GuiValidationSuccessTitle {
            get {
                return ResourceManager.GetString("GuiValidationSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter id.
        /// </summary>
        internal static string GuiValidationTextInputLabel {
            get {
                return ResourceManager.GetString("GuiValidationTextInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityCardNumber invalid control number.
        /// </summary>
        internal static string IdentityCardControlNumberValidationMessage {
            get {
                return ResourceManager.GetString("IdentityCardControlNumberValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Card Number cannot be composed only from 0 or 9 digits.
        /// </summary>
        internal static string IdentityCardNumberExtremeValuesValidationMessage {
            get {
                return ResourceManager.GetString("IdentityCardNumberExtremeValuesValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Card Number must contain some value.
        /// </summary>
        internal static string IdentityCardNumberNotEmptyMessage {
            get {
                return ResourceManager.GetString("IdentityCardNumberNotEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Card Number numeric part should contains only digits.
        /// </summary>
        internal static string IdentityCardNumberNumericPartValidationMessage {
            get {
                return ResourceManager.GetString("IdentityCardNumberNumericPartValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Card Number prefix must contain only upper ascii characters.
        /// </summary>
        internal static string IdentityCardNumberPrefixPartValidationMessage {
            get {
                return ResourceManager.GetString("IdentityCardNumberPrefixPartValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Card Number must be 9 characters long.
        /// </summary>
        internal static string IdentityCardNumberValidationLengthMessage {
            get {
                return ResourceManager.GetString("IdentityCardNumberValidationLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish Data Generator.
        /// </summary>
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP invalid control number.
        /// </summary>
        internal static string NipValidationControlNumberMessage {
            get {
                return ResourceManager.GetString("NipValidationControlNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP cannot be composed only from 0 or 9 digits.
        /// </summary>
        internal static string NipValidationExtremeValuesMessage {
            get {
                return ResourceManager.GetString("NipValidationExtremeValuesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP must have as a prefix (first 3 digits) the valid tax office number.
        /// </summary>
        internal static string NipValidationInvalidPrefix {
            get {
                return ResourceManager.GetString("NipValidationInvalidPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP must be 10 characters long.
        /// </summary>
        internal static string NipValidationLengthMessage {
            get {
                return ResourceManager.GetString("NipValidationLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP must contain some value.
        /// </summary>
        internal static string NipValidationNotEmptyMessage {
            get {
                return ResourceManager.GetString("NipValidationNotEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP must contain only digits.
        /// </summary>
        internal static string NipValidationOnlyDigitsMessage {
            get {
                return ResourceManager.GetString("NipValidationOnlyDigitsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESEL invalid control number.
        /// </summary>
        internal static string PeselValidationControlNumberMessage {
            get {
                return ResourceManager.GetString("PeselValidationControlNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESEL Day part must be in range 1 to 31.
        /// </summary>
        internal static string PeselValidationDayRangeMessage {
            get {
                return ResourceManager.GetString("PeselValidationDayRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESEL cannot be composed only from 0 or 9 digits.
        /// </summary>
        internal static string PeselValidationExtremeValuesMessage {
            get {
                return ResourceManager.GetString("PeselValidationExtremeValuesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESEL must be 11 characters long.
        /// </summary>
        internal static string PeselValidationLengthMessage {
            get {
                return ResourceManager.GetString("PeselValidationLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESEL Month part must be in range 1 to 12.
        /// </summary>
        internal static string PeselValidationMonthRangeMessage {
            get {
                return ResourceManager.GetString("PeselValidationMonthRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESEL must contain some value.
        /// </summary>
        internal static string PeselValidationNotEmptyMessage {
            get {
                return ResourceManager.GetString("PeselValidationNotEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESEL must contain only digits.
        /// </summary>
        internal static string PeselValidationOnlyDigitsMessage {
            get {
                return ResourceManager.GetString("PeselValidationOnlyDigitsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Polish IDs.
        /// </summary>
        internal static string PolishDataGenLabel {
            get {
                return ResourceManager.GetString("PolishDataGenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON invalid control number.
        /// </summary>
        internal static string RegonValidationControlNumberMessage {
            get {
                return ResourceManager.GetString("RegonValidationControlNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON cannot be composed only from 0 or 9 digits.
        /// </summary>
        internal static string RegonValidationExtremeValuesMessage {
            get {
                return ResourceManager.GetString("RegonValidationExtremeValuesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON must be 9 or 14 characters long.
        /// </summary>
        internal static string RegonValidationLengthMessage {
            get {
                return ResourceManager.GetString("RegonValidationLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON must contain some value.
        /// </summary>
        internal static string RegonValidationNotEmptyMessage {
            get {
                return ResourceManager.GetString("RegonValidationNotEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON must contain only digits.
        /// </summary>
        internal static string RegonValidationOnlyDigitsMessage {
            get {
                return ResourceManager.GetString("RegonValidationOnlyDigitsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish Data Gen.
        /// </summary>
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
    }
}
