//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevToys.PolishDataGen.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PolishDataGen {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PolishDataGen() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevToys.PolishDataGen.Strings.PolishDataGen", typeof(PolishDataGen).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows generation of PESEL, NIP, REGON.
        /// </summary>
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when enabled app will run k = 1 + 3.3 * Log10(Number) jobs.
        /// </summary>
        internal static string CliEnableMultithreading {
            get {
                return ResourceManager.GetString("CliEnableMultithreading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select id generator type. Current available option is: Pesel.
        /// </summary>
        internal static string CliGeneratorType {
            get {
                return ResourceManager.GetString("CliGeneratorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With such large numbers it is recommended to use the CLI version.
        /// </summary>
        internal static string CliInfoBarContent {
            get {
                return ResourceManager.GetString("CliInfoBarContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string CliInfoBarTitle {
            get {
                return ResourceManager.GetString("CliInfoBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string CliMultiLineTextInputTitle {
            get {
                return ResourceManager.GetString("CliMultiLineTextInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the number of data to be generated.
        /// </summary>
        internal static string CliNumberPropertyDescription {
            get {
                return ResourceManager.GetString("CliNumberPropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to define output file path.
        /// </summary>
        internal static string CliOutputFilePath {
            get {
                return ResourceManager.GetString("CliOutputFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library for generating correct Polish identifiers: PESEL, NIP, REGON and more. Perfect for testing and validating systems..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear memory.
        /// </summary>
        internal static string GuiClearMemoryButtonLabel {
            get {
                return ResourceManager.GetString("GuiClearMemoryButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string GuiGenerateButtonLabel {
            get {
                return ResourceManager.GetString("GuiGenerateButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of data to generate.
        /// </summary>
        internal static string GuiNumberInputLabel {
            get {
                return ResourceManager.GetString("GuiNumberInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish Data Generator.
        /// </summary>
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESEL invalid control number.
        /// </summary>
        internal static string PeselValidationControlNumberMessage {
            get {
                return ResourceManager.GetString("PeselValidationControlNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESEL Day part must be in range 1 to 31.
        /// </summary>
        internal static string PeselValidationDayRangeMessage {
            get {
                return ResourceManager.GetString("PeselValidationDayRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESEL cannot be composed only from 0 or 9 digits.
        /// </summary>
        internal static string PeselValidationExtremeValuesMessage {
            get {
                return ResourceManager.GetString("PeselValidationExtremeValuesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESEL must be 11 characters long.
        /// </summary>
        internal static string PeselValidationLengthMessage {
            get {
                return ResourceManager.GetString("PeselValidationLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESEL Month part must be in range 1 to 12.
        /// </summary>
        internal static string PeselValidationMonthRangeMessage {
            get {
                return ResourceManager.GetString("PeselValidationMonthRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESEL must contain some value.
        /// </summary>
        internal static string PeselValidationNotEmptyMessage {
            get {
                return ResourceManager.GetString("PeselValidationNotEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PESEL must contain only digits.
        /// </summary>
        internal static string PeselValidationOnlyDigitsMessage {
            get {
                return ResourceManager.GetString("PeselValidationOnlyDigitsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Polish IDs.
        /// </summary>
        internal static string PolishDataGenLabel {
            get {
                return ResourceManager.GetString("PolishDataGenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON invalid control number.
        /// </summary>
        internal static string RegonValidationControlNumberMessage {
            get {
                return ResourceManager.GetString("RegonValidationControlNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON cannot be composed only from 0 or 9 digits.
        /// </summary>
        internal static string RegonValidationExtremeValuesMessage {
            get {
                return ResourceManager.GetString("RegonValidationExtremeValuesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON must be 9 or 14 characters long.
        /// </summary>
        internal static string RegonValidationLengthMessage {
            get {
                return ResourceManager.GetString("RegonValidationLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON must contain some value.
        /// </summary>
        internal static string RegonValidationNotEmptyMessage {
            get {
                return ResourceManager.GetString("RegonValidationNotEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON must contain only digits.
        /// </summary>
        internal static string RegonValidationOnlyDigitsMessage {
            get {
                return ResourceManager.GetString("RegonValidationOnlyDigitsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish Data Gen.
        /// </summary>
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
    }
}
